name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api:
        image: mwinteringham/restfulbooker:latest
        ports:
          - 3001:3001

    env:
      BASE_URL: http://localhost:3001/
      RUN_UI_TESTS: "false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for API to be ready
        run: sleep 10  # Add a delay to ensure the API service is ready

      - name: Print API service logs
        run: docker logs $(docker ps -q --filter "ancestor=mwinteringham/restfulbooker:latest")

      - name: Run API tests
        run: behave features/api.feature